# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '使用者信息',
                'verbose_name_plural': '使用者信息',
            },
        ),
    ]
